# Generated by Django 3.2.5 on 2021-07-31 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orkut', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertable',
            old_name='name',
            new_name='firstname',
        ),
    ]
