# Generated by Django 3.2.5 on 2021-07-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orkut', '0002_rename_name_usertable_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
